[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Free plan configuration
[build.healthcheck]
path = "/api/health"
# Triggered redeploy to fix frontend loading issue

[[services]]
name = "labubu-backend"
sourceDir = "backend"
