// List of countries (ISO 3166, common names)
const countries: string[] = [
  "United States",
  "Canada",
  "United Kingdom",
  "Australia",
  "Italy",
  "France",
  "Germany",
  "Spain",
  "Netherlands",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Ireland",
  "Switzerland",
  "Austria",
  "Belgium",
  "Portugal",
  "Greece",
  "Poland",
  "Czech Republic",
  "Hungary",
  "Romania",
  "Bulgaria",
  "Slovakia",
  "Slovenia",
  "Croatia",
  "Estonia",
  "Latvia",
  "Lithuania",
  "Luxembourg",
  "Malta",
  "Cyprus",
  "Russia",
  "Turkey",
  "India",
  "China",
  "Japan",
  "South Korea",
  "Brazil",
  "Mexico",
  "Argentina",
  "Chile",
  "Colombia",
  "South Africa",
  "Egypt",
  "Israel",
  "Saudi Arabia",
  "United Arab Emirates",
  "New Zealand",
  // ...add more as needed
];

export default countries; 